Files already downloaded and verified
Files already downloaded and verified
| ID | GPU | MEM |
------------------
|  0 |  0% |  5% |
|  1 |  0% |  0% |
#######################################################
Avg Validation Stats after 1 global rounds
Validation Loss     : 2.11
Validation Accuracy : top1/top5 24.06%/76.96%
#######################################################
Took 177.74395895004272s
| ID | GPU | MEM |
------------------
|  0 |  0% | 23% |
|  1 |  0% | 10% |
Traceback (most recent call last):
  File "/home/kwangyeongill/FedSSL_recent/main.py", line 131, in <module>
    weight = q.get()
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/multiprocessing/queues.py", line 103, in get
    res = self._recv_bytes()
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/multiprocessing/connection.py", line 221, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/multiprocessing/connection.py", line 419, in _recv_bytes
    buf = self._recv(4)
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/multiprocessing/connection.py", line 384, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
Exception ignored in: <module 'threading' from '/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/threading.py", line 1448, in _shutdown
    lock.acquire()
KeyboardInterrupt: