Files already downloaded and verified
Files already downloaded and verified
| ID | GPU | MEM |
------------------
|  0 |  0% |  5% |
#######################################################
Avg Validation Stats after 1 global rounds
Validation Loss     : 2.12
Validation Accuracy : top1/top5 23.14%/72.86%
#######################################################
Took 186.5229890346527s
#######################################################
Avg Validation Stats after 2 global rounds
Validation Loss     : 2.14
Validation Accuracy : top1/top5 22.84%/72.12%
#######################################################
Took 181.52254819869995s
Traceback (most recent call last):
  File "/home/kwangyeongill/FedSSL_recent/main.py", line 64, in <module>
    state_dict = train_server_model(
  File "/home/kwangyeongill/FedSSL_recent/trainers.py", line 72, in train_server_model
    for batch_idx, (images, labels) in enumerate(loader):
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 368, in __iter__
    return self._get_iterator()
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 314, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 927, in __init__
    w.start()
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 62, in _launch
    f.write(fp.getbuffer())
KeyboardInterrupt
Exception ignored in: <module 'threading' from '/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/home/kwangyeongill/anaconda/envs/FedSSL/lib/python3.9/threading.py", line 1448, in _shutdown
    lock.acquire()
KeyboardInterrupt: