
Files already downloaded and verified
Traceback (most recent call last):
  File "/home/kwangyeongill/FedSSL_recent/main.py", line 39, in <module>
    train_set = CIFAR10_Train(args)
  File "/home/kwangyeongill/FedSSL_recent/data_utils.py", line 111, in __init__
    self.client_transform = transforms[args.exp]
KeyError: 'FedBYOL'